src/main/java/com/semsoftware/core/model/Booking.java
package com.semsoftware.core.model;

import javax.persistence.*;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@Entity
@Table(name = "booking")
public class Booking implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @ManyToMany(cascade=CascadeType.MERGE)
    @JoinTable(name = "client_booking_mm", joinColumns = @JoinColumn(name = "booking_id"),
            inverseJoinColumns = @JoinColumn(name = "client_id"))
    private List<Client> clients = new ArrayList<Client>();

    @ManyToMany(cascade = CascadeType.MERGE)
    @JoinTable(name = "room_booking_mm", joinColumns = @JoinColumn(name = "booking_id"),
            inverseJoinColumns = @JoinColumn(name = "room_id"))
    private List<Room> rooms = new ArrayList<Room>();

    @Column(name = "price")
    private Double price;

    // in days
    @Column(name = "duration")
    private Integer duration;
    
    @Column(name = "dateFrom")
    private Date dateFrom;
    
    @Column(name = "dateTo")
    private Date dateTo;
    
    @Column(name = "cancel")
    private Boolean cancel;


    /**
     * default constructor for hibernate
     */
    public Booking() {
    }


    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public List<Client> getClients() {
        return clients;
    }

    public void setClients(List<Client> clients) {
        this.clients = clients;
    }

    public List<Room> getRooms() {
        return rooms;
    }

    public void setRooms(List<Room> rooms) {
        this.rooms = rooms;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public Integer getDuration() {
        return duration;
    }

    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    public Date getDateFrom() {
      return dateFrom;
    }

    public void setDateFrom(Date dateFrom) {
      this.dateFrom = dateFrom;
    }

    public Date getDateTo() {
      return dateTo;
    }

    public void setDateTo(Date dateTo) {
      this.dateTo = dateTo;
    }


    public Boolean getCancel() {
      return cancel;
    }


    public void setCancel(Boolean cancel) {
      this.cancel = cancel;
    }
    
    
    
}

src/main/java/com/semsoftware/core/controllers/BookingBean.java
package com.semsoftware.core.controllers;


import com.semsoftware.core.controllers.user.App;
import com.semsoftware.core.dto.BookingDTO;
import com.semsoftware.core.dto.ClientDTO;
import com.semsoftware.core.dto.RoomDTO;
import com.semsoftware.core.facade.BookingFacade;
import com.semsoftware.core.facade.ClientFacade;
import com.semsoftware.core.facade.RoomFacade;
import com.semsoftware.core.util.PrimeFacesUtil;
import org.primefaces.event.FlowEvent;
import org.primefaces.event.SelectEvent;
import org.springframework.context.annotation.Scope;

import javax.annotation.PostConstruct;
import javax.faces.event.AjaxBehaviorEvent;
import javax.inject.Inject;
import javax.inject.Named;
import java.io.Serializable;
import java.util.*;

@Named("bookingBean")
@Scope("view")
public class BookingBean implements Serializable{

  /**
   * 
   */
  private static final long serialVersionUID = 1L;

  @Inject
  private NavigationBean navigation;
  @Inject
  private App app;
  @Inject
  private BookingFacade bookingFacade;
  @Inject
  private ClientFacade clientFacade;
  @Inject
  private RoomFacade roomFacade;
  
  private List<BookingDTO> bookings;
  private List<ClientDTO> clients;
  private List<ClientDTO> selectedClients = new ArrayList<ClientDTO>();
  private String[] selectedClientsStr;   
  private List<String> clientsStr;
  private List<RoomDTO> rooms;
  private RoomDTO selectedRoom;
  private List<RoomDTO> selectedRooms=new ArrayList<RoomDTO>();
  private String selectedRoomsStr="";   
  private List<String> roomsStr;
  private double price=0.0, total=0.0;
  private Integer duration;
  private Date dateFrom;
  private Date dateTo;
  private String roomList;
  private HashMap<RoomDTO, Double> roomMap = new HashMap<RoomDTO, Double>();
  private List<String> roomAndPreis =  new ArrayList<String>();
  private Integer erwachseneNr=1, kinderNr=0;
  private ArrayList<Integer> selectedRoomIds = new ArrayList<Integer>();
  private Date today;
  private Date dateFromPlusOne;
  private String returnPage;
  private BookingDTO booking;  
  
  @PostConstruct
  public void init() {
    
    final Map<String, String> requestParameterMap = PrimeFacesUtil.getRequestParameterMap();
    if (requestParameterMap != null) {
      String bookingId = requestParameterMap.get("bookingId");
      returnPage = requestParameterMap.get("returnPage");
      
      if(bookingId!=null){
        booking = bookingFacade.getBookingOnId(Integer.parseInt(bookingId));
        dateFrom = booking.getDateFrom();
        dateTo = booking.getDateTo();
        duration = booking.getDuration();
        total = booking.getPrice();
        selectedClients = booking.getClients();
        selectedClientsStr = new String[selectedClients.size()];
        int i=0;
        for(ClientDTO c: selectedClients){
          selectedClientsStr[i] = (c.getId()+" "+c.getFirstName()+" "+c.getLastName());
          i++;
        }
      }else{
        booking = new BookingDTO();
      }
      
    }
    
    bookings = bookingFacade.findActiveBookings();
    clients = clientFacade.getAllClientDTOs();
    makeClientList();

    rooms = roomFacade.findAll();    
    
    
  }

  public BookingDTO getBooking() {
    return booking;
  }

  public void setBooking(BookingDTO booking) {
    this.booking = booking;
  }

  public void makeClientList(){
    
    clientsStr =  new ArrayList<String>();
    for(ClientDTO c: clients){
      clientsStr.add(c.getId()+" "+c.getFirstName()+" "+c.getLastName());
    }
    
  }

  public String createBooking() {
//    BookingDTO bookingDTO = new BookingDTO();
    
    for(ClientDTO c: selectedClients){
      System.out.println(c.getId());
    }
    booking.setClients(selectedClients);
    booking.setRooms(selectedRooms);
    booking.setDateFrom(dateFrom);
    booking.setDateTo(dateTo);
    booking.setPrice(getTotal());
    
    booking.setCancel(false);

    booking.setDuration(duration);

    bookingFacade.saveBooking(booking);

    return navigation.getPageBookingList();
  }
  
  public void refreshZimmerListe(){
    int max = erwachseneNr;
    roomsStr =  new ArrayList<String>();
    System.out.println(max);
    boolean addRoom=true;
    List<BookingDTO> bookingsBetweenDates = bookingFacade.findBookingsBetweenDates(dateFrom, dateTo);
    System.out.println("bookingsBetweenDates size: "+bookingsBetweenDates.size());
    for(RoomDTO r: rooms){
        if(r.getMaxPeople()>= max && !selectedRoomIds.contains(r.getId())){
          for(BookingDTO b: bookingsBetweenDates){
            List<RoomDTO> listroom= b.getRooms();
            for(RoomDTO r2: listroom){
  //            System.out.println(r2.getId()+" "+r2.getName());
              if(r2.getId()==r.getId()){ 
                  
                    addRoom=false;
                  
              
              }
              
            }
          }
          
          if(addRoom==true){
            roomsStr.add(r.getId()+" "+r.getName());
              if (selectedRoomsStr == null) {
                  selectedRoomsStr = r.getId()+" "+r.getName();
              }
          }
        }
        addRoom=true;
    }

    
  }
  
  public void addZimmer(){
      if (selectedRoomsStr != null) {
          String[] str = selectedRoomsStr.split("\\s+");
          try {
              int id = Integer.parseInt(str[0]);

              for (RoomDTO r : rooms) {
                  if (id == r.getId()) {
                      selectedRoom = r;
                  }
              }
              double preis = 0;
              if (erwachseneNr == 1) {
                  preis += selectedRoom.getPriceSingle();
              } else {
                  preis += selectedRoom.getPriceMax();
              }
              if (kinderNr != 0) {
                  preis += (selectedRoom.getPriceForChild()) * kinderNr;
              }
              roomMap.put(selectedRoom, preis);
              selectedRooms.add(selectedRoom);
              setPrice(preis);
              selectedRoomIds.add(selectedRoom.getId());
              roomAndPreis.add(selectedRoom.getId() + " " + selectedRoom.getName() + " - Preis: " + preis);
              //refreshZimmerListe();
          } catch (Exception e) {
              e.printStackTrace();
          }
      }
  }
  
  public List<BookingDTO> getBookings() {
    return bookings;
  }

  public void setBookings(List<BookingDTO> bookings) {
    this.bookings = bookings;
  }

  public List<ClientDTO> getClients() {
    return clients;
  }

  public void setClients(List<ClientDTO> clients) {
    this.clients = clients;
  }

  public List<ClientDTO> getSelectedClients() {
    return selectedClients;
  }

  public void setSelectedClients(List<ClientDTO> selectedClients) {
    this.selectedClients = selectedClients;
  }

  public String[] getSelectedClientsStr() {
    return selectedClientsStr;
  }

  public void setSelectedClientsStr(String[] selectedClientsStr) {
    this.selectedClientsStr = selectedClientsStr;
  }

  public List<String> getClientsStr() {
    return clientsStr;
  }

  public void setClientsStr(List<String> clientsStr) {
    this.clientsStr = clientsStr;
  }

  public List<RoomDTO> getRooms() {
    return rooms;
  }

  public void setRooms(List<RoomDTO> rooms) {
    this.rooms = rooms;
  }

  public List<RoomDTO> getSelectedRooms() {
    return selectedRooms;
  }

  public void setSelectedRooms(List<RoomDTO> selectedRooms) {
    this.selectedRooms = selectedRooms;
  }

  public String getSelectedRoomsStr() {
    return selectedRoomsStr;
  }

  public void setSelectedRoomsStr(String selectedRoomsStr) {
    this.selectedRoomsStr = selectedRoomsStr;
  }

  public List<String> getRoomsStr() {
    return roomsStr;
  }

  public void setRoomsStr(List<String> roomsStr) {
    this.roomsStr = roomsStr;
  }

  public double getPrice() {

    double p=0;
    for (Map.Entry<RoomDTO, Double> entry : roomMap.entrySet()) {
       p+=entry.getValue();
    }
    
    setPrice(p);
    return price;
  }

  public void setPrice(double price) {
    this.price = price;

  }

  public Integer getDuration() {
    return duration;
  }

  public void setDuration(Integer duration) {
    this.duration = duration;
  }

  public Date getDateFrom() {
    return dateFrom;
  }

  public void setDateFrom(Date dateFrom) {
    this.dateFrom = dateFrom;
  }

  public Date getDateTo() {
    return dateTo;
  }

  public void setDateTo(Date dateTo) {
    this.dateTo = dateTo;
  }

  public String getRoomList() {
    return roomList;
  }

  public void setRoomList(String roomList) {
    this.roomList = roomList;
  }

  public HashMap<RoomDTO, Double> getRoomMap() {
    return roomMap;
  }

  public void setRoomMap(HashMap<RoomDTO, Double> roomMap) {
    this.roomMap = roomMap;
  }

  public RoomDTO getSelectedRoom() {
    return selectedRoom;
  }

  public void setSelectedRoom(RoomDTO selectedRoom) {
    this.selectedRoom = selectedRoom;
  }

  public Integer getKinderNr() {
    return kinderNr;
  }

  public void setKinderNr(Integer kinderNr) {
    this.kinderNr = kinderNr;
  }

  public Integer getErwachseneNr() {
    return erwachseneNr;
  }

  public void setErwachseneNr(Integer erwachseneNr) {
    this.erwachseneNr = erwachseneNr;
  }
  
  public String onFlowProcess(FlowEvent event) {
    
    if(event.getNewStep().equals("preis")){
      if(roomAndPreis.size()>0){
        return event.getNewStep();
      }else {
        return "zimmer";
      }
    }
    if(event.getNewStep().equals("zimmer")){
      duration = (int) ((getDateTo().getTime() - getDateFrom().getTime()) / (1000 * 60 * 60 * 24));
    }
    if(event.getNewStep().equals("datum")){
      selectedClients= new ArrayList<ClientDTO>();
      for (int i = 0; i < getSelectedClientsStr().length; i++) {
        String[] splitted = getSelectedClientsStr()[i].split("\\s+");
        for (ClientDTO c : clients) {
          if (c.getId().toString().equals(splitted[0]) && !selectedClients.contains(c)) {
            selectedClients.add(c);
          }
        }
      }

src/main/java/com/semsoftware/core/controllers/NavigationBean.java
package com.semsoftware.core.controllers;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Scope;

import javax.annotation.PostConstruct;
import javax.inject.Named;
import java.io.Serializable;

/**
 * 
 * @author ozdesimsek
 *
 */
@Named("navigation")
@Scope("session")
public class NavigationBean implements Serializable{

  private static final Logger logger = LoggerFactory.getLogger(NavigationBean.class);

  private final static String PAGE_INDEX = "/public/index";
  private final static String PAGE_HOME = "/pages/main";

  private final static String PAGE_REGISTER = "/public/user/register";

  private final static String PAGE_SEARCH = "/pages/search";
  private final static String PAGE_SEARCH_RESULT = "/pages/search/result";

  private final static String PAGE_RECEIPT_LIST = "/pages/receipts/list";
  private final static String PAGE_BOOKING_LIST = "/pages/bookings/listBooking";
  private final static String PAGE_CLIENT_LIST = "/pages/clients/list";

  private final static String PAGE_CREATE_CLIENT = "/pages/clients/createClient";
  private final static String PAGE_CREATE_BOOKING = "/pages/bookings/createBooking";
  
  private final static String PAGE_ROOMS_LIST = "/pages/rooms/list";


  @PostConstruct
  public void init() {
    logger.info("Bean created");
  }

  public String getPageIndex() {
    return  PAGE_INDEX;
  }

  public String getPageHome() {
    return  PAGE_HOME;
  }

  public String getPageRegister() {
    return  PAGE_REGISTER;
  }

  public String getPageReceiptList() {
    return PAGE_RECEIPT_LIST;
  }

  public String getPageBookingList() {
    return PAGE_BOOKING_LIST;
  }

  public String getPageClientList() {
    return PAGE_CLIENT_LIST;
  }

  public String getPageCreateClient() {
    return PAGE_CREATE_CLIENT;
  }

  public String getPageSearch() {
    return PAGE_SEARCH;
  }

  public String getPageSearchResult() {
    return PAGE_SEARCH_RESULT;
  }
  
  public String getPageCreateBooking(){
    return PAGE_CREATE_BOOKING;
  }

  public String getPageRoomsList() {
    return PAGE_ROOMS_LIST;
  }
}

src/main/webapp/pages/bookings/createBooking.xhtml
<ui:composition template="/templates/main.xhtml"
				xmlns="http://www.w3.org/1999/xhtml"
				xmlns:ui="http://java.sun.com/jsf/facelets"
				xmlns:p="http://primefaces.org/ui"
				xmlns:f="http://java.sun.com/jsf/core"
				xmlns:h="http://java.sun.com/jsf/html">

	<ui:define name="content">
		<h1 class="page-header">
		#{bookingBean.booking.id eq null ? msg.newBooking
			: msg.editBooking}
		</h1>
		<h:form id="form">
			<p:messages id="messages" />
			<p:wizard flowListener="#{bookingBean.onFlowProcess}">
			<p:tab id="kunden" title="Kunden">
				<p:panelGrid>
					<p:row>
						<p:column colspan="2">
							<p:outputLabel for="menu" value="Kunden:"
								style="font-weight:bold" />
						</p:column>
						<p:column>
							<p:selectCheckboxMenu id="menu" value="#{bookingBean.selectedClientsStr}" label="Kunden auswählen"
                              filter="true" filterMatchMode="startsWith" required="true">
            				<f:selectItems value="#{bookingBean.clientsStr}" />
            				<p:ajax update="selectedClients" />
        					</p:selectCheckboxMenu>
						</p:column>
					</p:row>
					<p:row>
						<p:column colspan="2">
							<p:outputLabel for="selectedClients" value="Gewählte Kunden:"
								style="font-weight:bold" />
						</p:column>
						<p:column>
							<p:dataList id="selectedClients" value="#{bookingBean.selectedClientsStr}" var="client" type="ordered">
								#{client}
						    </p:dataList>
						</p:column>
					</p:row>
				</p:panelGrid>
			</p:tab>
			<p:tab id="datum" title="Datum">
				<p:panelGrid>
					<p:row>
						<p:column colspan="2">
							<p:outputLabel for="dateFrom" value="#{msg['lDateFrom']}"
										   style="font-weight:bold"/>
						</p:column>
						<p:column>
							<p:calendar id="dateFrom"
										value="#{bookingBean.dateFrom}" mindate="#{bookingBean.today}"
										navigator="true" yearRange="c-100:c-0" pattern="dd-MMM-yyyy" required="true">
										<f:ajax event="dateSelect" listener="#{bookingBean.updateDateTo}" render="dateTo"/>
							</p:calendar>
						</p:column>
					</p:row>
					<p:row>
						<p:column colspan="2">
							<p:outputLabel for="dateTo" value="#{msg['lDateTo']}"
										   style="font-weight:bold"/>
						</p:column>
						<p:column>
							<p:calendar id="dateTo"
										value="#{bookingBean.dateTo}" required="true" mindate="#{bookingBean.dateFromPlusOne}" 
										navigator="true" yearRange="c-100:c-0" pattern="dd-MMM-yyyy"/>
						</p:column>
					</p:row>
				</p:panelGrid>
			</p:tab>
			<p:tab id="zimmer" title="Zimmer">
				
				<p:panelGrid>
					
					
					<p:row>
						<p:column colspan="2">
						<h:outputLabel for="basic" value="Erwachsenenanzahl: " />
						</p:column>
						<p:column>
        				<p:spinner id="basic" value="#{bookingBean.erwachseneNr}" >
        				<f:ajax process="@this"/>
        				</p:spinner>
        				</p:column>
       				</p:row>
       				<p:row>
        				<p:column colspan="2">
						<h:outputLabel for="basic2" value="Kinderanzahl: " />
						</p:column>
						<p:column>
        				<p:spinner id="basic2" value="#{bookingBean.kinderNr}" >
        					<f:ajax process="@this"/>
        				</p:spinner>
        				</p:column>
					</p:row>
					<p:row>
						<p:column>
							<p:commandButton value="Zimmerliste laden" icon="ui-icon-extlink" >
								<f:ajax render="menu2" listener="#{bookingBean.refreshZimmerListe}"/>
							</p:commandButton>
						</p:column>
						
					</p:row>
					<p:row>
						<p:column colspan="2">
							<p:outputLabel for="menu2" value="Zimmer:"
								style="font-weight:bold" />
						</p:column>
						<p:column>
							<p:panelGrid>
								<p:row>
									<p:column>
										<p:selectOneMenu id="menu2" value="#{bookingBean.selectedRoomsStr}" label="Zimmer auswählen">
											<f:ajax process="@this"/>
			                              <f:selectItem itemLabel="Zimmer auswählen" itemValue="" itemDisabled="true"/>
			            				<f:selectItems value="#{bookingBean.roomsStr}" />
			        					</p:selectOneMenu>
									</p:column>
									<p:column>
										<p:commandButton value="Hinzufügen">
											<f:ajax listener="#{bookingBean.addZimmer()}" render="rt" icon="ui-icon-plus"/>
										</p:commandButton>
									</p:column>
								</p:row>
							
							</p:panelGrid>
							
						</p:column>
					</p:row>
					<p:row id="gzRow">
						<p:column colspan="2">
							<p:outputLabel for="rt" value="Gewählte Zimmer:"
								style="font-weight:bold" />
						</p:column>
						
						<p:column>
							<p:dataList id="rt" value="#{bookingBean.roomAndPreis}" var="r" emptyMessage="Keine Zimmer ausgewählt">
					            #{r}
					        </p:dataList>
						</p:column>
					</p:row>					
				</p:panelGrid>
			</p:tab>
			<p:tab id="preis" title="Preis">
				<p:panelGrid>
					<p:row>
						<p:column colspan="2">
							<p:outputLabel for="price" value="Preis für 1 Nacht:"
										   style="font-weight:bold"/>
						</p:column>
						<p:column>
							<p:outputLabel id="price" value="#{bookingBean.price}" placeholder="0.0"/>
						</p:column>
					</p:row>
					<p:row>
						<p:column colspan="2">
							<p:outputLabel for="duration" value="Duration:"
										   style="font-weight:bold"/>
						</p:column>
						<p:column>
							<p:outputLabel id="duration" value="#{bookingBean.duration}" >
							</p:outputLabel>
						</p:column>
					</p:row>
					<p:row>
						<p:column colspan="2">
							<p:outputLabel for="total" value="Totalpreis:"
										   style="font-weight:bold"/>
						</p:column>
						<p:column>
							<p:outputLabel id="total" value="#{bookingBean.total}" >
							</p:outputLabel>
						</p:column>
					</p:row>
				</p:panelGrid>
			</p:tab>
			<p:tab id="summary" title="Zusammenfassung">
				<p:panelGrid>
					<p:row>
						<p:column colspan="2">
							<p:outputLabel for="selectedClientsZ" value="Gewählte Kunden:"
								style="font-weight:bold" />
						</p:column>
						<p:column>
							<p:dataList id="selectedClientsZ" value="#{bookingBean.selectedClientsStr}" var="client" type="ordered">
								#{client}
						    </p:dataList>
						</p:column>
					</p:row>
					<p:row>
						<p:column colspan="2">
							<p:outputLabel for="dateFromZ" value="#{msg['lDateFrom']}"
										   style="font-weight:bold"/>
						</p:column>
						<p:column>
							<p:outputLabel id="dateFromZ"
										value="#{bookingBean.dateFrom}">
										<f:convertDateTime pattern="dd-MMM-yyyy" timeZone="GMT+3"/>
							</p:outputLabel>
						</p:column>
					</p:row>
					<p:row>
						<p:column colspan="2">
							<p:outputLabel for="dateToZ" value="#{msg['lDateTo']}"
										   style="font-weight:bold"/>
						</p:column>
						<p:column>
							<p:outputLabel id="dateToZ"
										value="#{bookingBean.dateTo}" pattern="yyyy-MMM-dd">
										<f:convertDateTime pattern="dd-MMM-yyyy" timeZone="GMT+3"/>
							</p:outputLabel>
						</p:column>
					</p:row>												
					
					<p:row >
						<p:column colspan="2">
							<p:outputLabel for="rtz" value="Gewählte Zimmer:"
								style="font-weight:bold" />
						</p:column>
						
						<p:column>
							<p:dataList id="rtz" value="#{bookingBean.roomAndPreis}" var="r" emptyMessage="Keine Zimmer ausgewählt">
					            #{r}
					        </p:dataList>
						</p:column>
					</p:row>
					<p:row>
						<p:column colspan="2">
							<p:outputLabel for="pricez" value="Preis für 1 Nacht:"
										   style="font-weight:bold"/>
						</p:column>
						<p:column>
							<p:outputLabel id="pricez" value="#{bookingBean.price}" placeholder="0.0"/>
						</p:column>
					</p:row>
					<p:row>
						<p:column colspan="2">
							<p:outputLabel for="durationz" value="Duration:"
										   style="font-weight:bold"/>
						</p:column>
						<p:column>
							<p:outputLabel id="durationz" value="#{bookingBean.duration}" >
							</p:outputLabel>
						</p:column>
					</p:row>
					<p:row>
						<p:column colspan="2">
							<p:outputLabel for="totalz" value="Totalpreis:"
										   style="font-weight:bold"/>
						</p:column>
						<p:column>
							<p:outputLabel id="totalz" value="#{bookingBean.total}" >
							</p:outputLabel>
						</p:column>
					</p:row>
					<p:row>
						<p:column colspan="3">
							<p:commandButton value="#{bookingBean.booking.id eq null ? msg['create'] :msg.save}"
											 action="#{bookingBean.createBooking}" update="form"/>
						</p:column>
					</p:row>
				</p:panelGrid>
			</p:tab>
			</p:wizard>
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/pages/bookings/listBooking.xhtml
<ui:composition template="/templates/main.xhtml"
				xmlns="http://www.w3.org/1999/xhtml"
				xmlns:ui="http://java.sun.com/jsf/facelets"
				xmlns:p="http://primefaces.org/ui"
				xmlns:f="http://java.sun.com/jsf/core"
				xmlns:h="http://java.sun.com/jsf/html">

	<ui:define name="content">
		<h1 class="page-header">
			Buchungsliste
		</h1>
		<h:form id="form">
		<p:panel>

		<p:inputSwitch value="#{bookingList.cancel}" onLabel="Aktiv" offLabel="Storniert" >
            <p:ajax listener="#{bookingList.loadBookings}" update="bookings" />
        </p:inputSwitch>
			<p:dataTable id="bookings" var="booking" value="#{bookingList.bookings}"
					rowKey="#{booking.id}" emptyMessage="Kein Eintrag vorhanden">

				<p:column headerText="Buchung ID" sortBy="#{booking.id}">
					<h:outputText value="#{booking.id}" />
				</p:column>

				<p:column headerText="Kunde" sortBy="#{booking.clients}" style="width:200px;text-align: center">
					<p:dataList value="#{booking.clients}" var="client" type="ordered">
						#{client.id}, #{client.firstName} #{client.lastName}
					</p:dataList>
				</p:column>

				<p:column headerText="Zimmer" sortBy="#{booking.rooms}" style="width:200px;text-align: center">
					<p:dataList value="#{booking.rooms}" var="room" type="ordered">
						#{room.id}, #{room.name}
					</p:dataList>
				</p:column>

				<p:column headerText="Preis" sortBy="#{booking.price}">
					<h:outputText value="#{booking.price}" />
				</p:column>

				<p:column headerText="Datum von" sortBy="#{booking.dateFrom}">
					<h:outputText value="#{booking.dateFrom}">
						<f:convertDateTime pattern="MM-dd-yyyy" timeZone="GMT+3"/>
					</h:outputText>
				</p:column>

				<p:column headerText="Datum bis" sortBy="#{booking.dateTo}">
					<h:outputText value="#{booking.dateTo}">
						<f:convertDateTime pattern="MM-dd-yyyy" timeZone="GMT+3"/>
					</h:outputText>
				</p:column>

				<p:column headerText="Dauer" sortBy="#{booking.duration}">
					<h:outputText value="#{booking.duration}"/>
				</p:column>

				<p:column>
					<p:commandButton
							action="#{bookingActions.editBooking(booking,navigation.pageBookingList)}"
							id="edit" icon="fa fa-edit" title="Editieren" ajax="false" rendered="#{!booking.cancel}"/>

					<p:commandButton ajax="false" icon="fa fa-file-pdf-o" rendered="#{!booking.cancel}">
						<p:fileDownload value="#{invoicePdf.createPdf(booking)}" />
					</p:commandButton>
					
					<p:commandButton
							action="#{bookingActions.cancelBooking(booking,navigation.pageBookingList)}"
							id="cancel" icon="fa fa-trash" ajax="false" title="Stornieren" rendered="#{!booking.cancel}" />
				</p:column>
				</p:dataTable>
			</p:panel>
			</h:form>

	</ui:define>
</ui:composition>